name: localization_checker
description: A CLI tool that scans Flutter apps to detect non-localized strings.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
executables:
  loc_checker: bin/main.dart
environment:
  sdk:  '>=3.5.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.8.3
  glob: ^2.1.2
  colorize: ^3.0.0
  yaml: ^3.1.2
  file: ^7.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
